version: "3"

services:
  bot:
    build: bot/
    command: python ./bot.py
    container_name: bot
    environment:
      BOT_TOKEN: TOKEN
      API_HOST: api
    networks:
      - memnet
    
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 80"
    container_name: api
    networks:
      - memnet
    ports:
      - "80:80"
networks:
  memnet:
    name: memnet
